[Dispatch File]
File Version       = 1.0
Show ID            = BIG
Show Name          = Cosmic Consensus Netshow

Update Script Server Path   = bigidea/content/UpdateScript.ini
BOB Update Script Server Path   = bigidea/content/ChangeoverUpdateScript.ini
Content Server Section      = Content Server
Game List Server Section    = Game List Server

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;    Deprecated - old big support for conversion
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Register CGI Name           = cgi/bezreg0.cgi
Validate CGI Name           = cgi/acrval0.cgi
Query CGI Name              = cgi/bezquery0.cgi
Change CGI Name             = cgi/bezchange0.cgi
Sponsors CGI Name           = cgi-bin/bezsponsors.cgi

Registration Server Section = Registration Server
Web Server Section          = Web Server



;;;; Content Servers ;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Content Server 1]
HTTP Server Name     = 10.0.2.2
HTTP Server Port     = 8080


;;[Content Server 2]
;;HTTP Server Name     = 128.11.20.169
;;HTTP Server Port     = 8080

;;;; Game List Servers ;;;;;;;;;;;;;;;;;;;;;;;;;;

[Game List Server 1]
IRC Server Name      = 10.0.2.2
IRC Server Port      = 6666
IRC Server Password  =
IRC Channel Name     = Big_List
IRC Channel Password =
IRC Bot Nickname     = CosmicBot


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;    Deprecated - old big support for conversion
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


;;;; Registration Servers ;;;;;;;;;;;;;;;;;;;;;;

[Registration Server 1]
                       ;dispatch.jack.com
HTTP Server Name     = 10.0.2.2
HTTP Server Port     = 8080
;;;                       ;dev.jack.com
;;;HTTP Server Name     = 192.216.191.143
;;;HTTP Server Port     = 80
;;;HTTP Server Port     = 8042

;;;; Web Server ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Web Server]
HTTP Server Name     = 10.0.2.2
HTTP Server Port     = 8080  ;(commented out, no ":80" in URL)
Success Page         = cosmic/sponsors.html
Error Page	         = cosmic/trouble.html
