;fixed to set ad folder properly
;MUST PATCH GAME TO FULLY FIX - CHANGE \ TO /
[Update Script]
Script Version = 1.0
Show ID        = GTP
Show Name      = Get the Picture Netshow


1 Goto         = Set Ad Server Folder


[Server Version Folders]
1.0.0.26      = /picture/content/v1.0.0.26

[Set Ad Server Folder]
Command        = SET VARIABLE TO VALUE
Variable       = AdServerFolder
Value          = picture/content/ads

