;fixed to set ad folder properly and add in other category srf files
;MUST PATCH GAME TO FULLY FIX - CHANGE \ TO /
[Update Script]
Script Version = 1.0
Show ID        = ACR
Show Name      = Acrophobia Netshow


1 Goto         = Set Ad Server Folder
2 Goto         = Update Resources


[Server Version Folders]
1.0.0.29      = /acrophobia/content/ClientVersion1.6.0.151
1.2.0.130     = /acrophobia/content/ClientVersion1.6.0.151
1.0.24.84     = /acrophobia/content/ClientVersion1.6.0.151
1.0.18.79     = /acrophobia/content/ClientVersion1.6.0.151
1.0.4.72      = /acrophobia/content/ClientVersion1.6.0.151
1.0.20.80     = /acrophobia/content/ClientVersion1.6.0.151
1.0.21.80     = /acrophobia/content/ClientVersion1.6.0.151
1.1.0.114     = /acrophobia/content/ClientVersion1.6.0.151
1.5.0.142     = /acrophobia/content/ClientVersion1.6.0.151
1.6.0.151     = /acrophobia/content/ClientVersion1.6.0.151


[Set Ad Server Folder]
Command        = SET VARIABLE TO VALUE
Variable       = AdServerFolder
Value          = acrophobia/content/ads/


[Update Resources]
1 Goto         = Srf Folder (optional)

[Srf Folder (optional)]
1 Goto         = CatAniml.srf
2 Goto         = CatCurnt.srf
3 Goto         = CatFood.srf
4 Goto         = CatGeog.srf
5 Goto         = CatHist.srf
6 Goto         = CatMovie.srf
7 Goto         = CatMusi.srf
8 Goto         = CatPol.srf
9 Goto         = CatSci.srf
10 Goto        = CatSport.srf
11 Goto        = CatTV.srf

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; CatAniml.srf
[CatAniml.srf]
1 Goto         = If CatAniml.srf exists
2 Goto         = If CatAniml.srf does not exist

[If CatAniml.srf exists]
Command        = IF CLIENT_PATH NOTEQUALTO VERSION THEN UPDATE
Client Path    = Srf/CatAniml.srf
Version        = 1.0.20.80
Group Priority = 101
Mandatory      = FALSE

[If CatAniml.srf does not exist]
Command        = IF CLIENT_PATH DOESNOTEXIST THEN UPDATE
Client Path    = Srf/CatAniml.srf
Version        = 1.0.20.80
Group Priority = 101
Mandatory      = TRUE
 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; CatCurnt.srf
[CatCurnt.srf]
1 Goto         = If CatCurnt.srf exists
2 Goto         = If CatCurnt.srf does not exist

[If CatCurnt.srf exists]
Command        = IF CLIENT_PATH NOTEQUALTO VERSION THEN UPDATE
Client Path    = Srf/CatCurnt.srf
Version        = 1.0.20.80
Group Priority = 103
Mandatory      = FALSE

[If CatCurnt.srf does not exist]
Command        = IF CLIENT_PATH DOESNOTEXIST THEN UPDATE
Client Path    = Srf/CatCurnt.srf
Version        = 1.0.20.80
Group Priority = 103
Mandatory      = TRUE

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; CatFood.srf
[CatFood.srf]
1 Goto         = If CatFood.srf exists
2 Goto         = If CatFood.srf does not exist

[If CatFood.srf exists]
Command        = IF CLIENT_PATH NOTEQUALTO VERSION THEN UPDATE
Client Path    = Srf/CatFood.srf
Version        = 1.0.20.80
Group Priority = 104
Mandatory      = FALSE

[If CatFood.srf does not exist]
Command        = IF CLIENT_PATH DOESNOTEXIST THEN UPDATE
Client Path    = Srf/CatFood.srf
Version        = 1.0.20.80
Group Priority = 104
Mandatory      = TRUE

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; CatGeog.srf
[CatGeog.srf]
1 Goto         = If CatGeog.srf exists
2 Goto         = If CatGeog.srf does not exist

[If CatGeog.srf exists]
Command        = IF CLIENT_PATH NOTEQUALTO VERSION THEN UPDATE
Client Path    = Srf/CatGeog.srf
Version        = 1.0.20.80
Group Priority = 105
Mandatory      = FALSE

[If CatGeog.srf does not exist]
Command        = IF CLIENT_PATH DOESNOTEXIST THEN UPDATE
Client Path    = Srf/CatGeog.srf
Version        = 1.0.20.80
Group Priority = 105
Mandatory      = TRUE

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; CatHist.srf
[CatHist.srf]
1 Goto         = If CatHist.srf exists
2 Goto         = If CatHist.srf does not exist

[If CatHist.srf exists]
Command        = IF CLIENT_PATH NOTEQUALTO VERSION THEN UPDATE
Client Path    = Srf/CatHist.srf
Version        = 1.0.20.80
Group Priority = 106
Mandatory      = FALSE

[If CatHist.srf does not exist]
Command        = IF CLIENT_PATH DOESNOTEXIST THEN UPDATE
Client Path    = Srf/CatHist.srf
Version        = 1.0.20.80
Group Priority = 106
Mandatory      = TRUE

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; CatMovie.srf
[CatMovie.srf]
1 Goto         = If CatMovie.srf exists
2 Goto         = If CatMovie.srf does not exist

[If CatMovie.srf exists]
Command        = IF CLIENT_PATH NOTEQUALTO VERSION THEN UPDATE
Client Path    = Srf/CatMovie.srf
Version        = 1.0.20.80
Group Priority = 107
Mandatory      = FALSE

[If CatMovie.srf does not exist]
Command        = IF CLIENT_PATH DOESNOTEXIST THEN UPDATE
Client Path    = Srf/CatMovie.srf
Version        = 1.0.20.80
Group Priority = 107
Mandatory      = TRUE

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; CatMusi.srf
[CatMusi.srf]
1 Goto         = If CatMusi.srf exists
2 Goto         = If CatMusi.srf does not exist

[If CatMusi.srf exists]
Command        = IF CLIENT_PATH NOTEQUALTO VERSION THEN UPDATE
Client Path    = Srf/CatMusi.srf
Version        = 1.0.20.80
Group Priority = 108
Mandatory      = FALSE

[If CatMusi.srf does not exist]
Command        = IF CLIENT_PATH DOESNOTEXIST THEN UPDATE
Client Path    = Srf/CatMusi.srf
Version        = 1.0.20.80
Group Priority = 108
Mandatory      = TRUE

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; CatPol.srf
[CatPol.srf]
1 Goto         = If CatPol.srf exists
2 Goto         = If CatPol.srf does not exist

[If CatPol.srf exists]
Command        = IF CLIENT_PATH NOTEQUALTO VERSION THEN UPDATE
Client Path    = Srf/CatPol.srf
Version        = 1.0.20.80
Group Priority = 109
Mandatory      = FALSE

[If CatPol.srf does not exist]
Command        = IF CLIENT_PATH DOESNOTEXIST THEN UPDATE
Client Path    = Srf/CatPol.srf
Version        = 1.0.20.80
Group Priority = 109
Mandatory      = TRUE

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; CatSci.srf
[CatSci.srf]
1 Goto         = If CatSci.srf exists
2 Goto         = If CatSci.srf does not exist

[If CatSci.srf exists]
Command        = IF CLIENT_PATH NOTEQUALTO VERSION THEN UPDATE
Client Path    = Srf/CatSci.srf
Version        = 1.0.20.80
Group Priority = 110
Mandatory      = FALSE

[If CatSci.srf does not exist]
Command        = IF CLIENT_PATH DOESNOTEXIST THEN UPDATE
Client Path    = Srf/CatSci.srf
Version        = 1.0.20.80
Group Priority = 110
Mandatory      = TRUE

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; CatSport.srf
[CatSport.srf]
1 Goto         = If CatSport.srf exists
2 Goto         = If CatSport.srf does not exist

[If CatSport.srf exists]
Command        = IF CLIENT_PATH NOTEQUALTO VERSION THEN UPDATE
Client Path    = Srf/CatSport.srf
Version        = 1.0.20.80
Group Priority = 112
Mandatory      = FALSE

[If CatSport.srf does not exist]
Command        = IF CLIENT_PATH DOESNOTEXIST THEN UPDATE
Client Path    = Srf/CatSport.srf
Version        = 1.0.20.80
Group Priority = 112
Mandatory      = TRUE

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; CatTV.srf
[CatTV.srf]
1 Goto         = If CatTV.srf exists
2 Goto         = If CatTV.srf does not exist

[If CatTV.srf exists]
Command        = IF CLIENT_PATH NOTEQUALTO VERSION THEN UPDATE
Client Path    = Srf/CatTV.srf
Version        = 1.0.20.80
Group Priority = 113
Mandatory      = FALSE

[If CatTV.srf does not exist]
Command        = IF CLIENT_PATH DOESNOTEXIST THEN UPDATE
Client Path    = Srf/CatTV.srf
Version        = 1.0.20.80
Group Priority = 113
Mandatory      = TRUE

