;; FOR BEZERK REVIVED ONLY - DO NOT USE ANYWHERE ELSE
;; also for older version with older bezerk logo
[Dispatch File]
File Version       = 1.0
Show ID            = ACR
Show Name          = Acrophobia Netshow

Update Script Server Path   = /acrophobia/content/ChangeoverUpdateScript.ini
BOB Update Script Server Path   = /acrophobia/content/UpdateScript.ini
Content Server Section      = Content Server
Game List Server Section    = Game List Server

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;    Deprecated - old acro support for conversion
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Register CGI Name           = cgi/bezreg0.cgi
Validate CGI Name           = cgi/acrval1.cgi
Query CGI Name              = cgi/bezquery0.cgi
Change CGI Name             = cgi/bezchange0.cgi
Sponsors CGI Name           = /acro/sponsors.html

Registration Server Section = Registration Server
Web Server Section          = Web Server



;;;; Content Servers ;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Content Server 1]
HTTP Server Name     = 10.0.2.2
HTTP Server Port     = 8080


;;[Content Server 2]
;;HTTP Server Name     = 10.0.2.2
;;HTTP Server Port     = 8080

;;;; Game List Servers ;;;;;;;;;;;;;;;;;;;;;;;;;;

[Game List Server 1]
IRC Server Name      = 10.0.2.2
IRC Server Port      = 6666
IRC Server Password  =
IRC Channel Name     = Acro_List
IRC Channel Password =
IRC Bot Nickname     = Acrobot





;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;    Deprecated - old acro support for conversion
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


;;;; Registration Servers ;;;;;;;;;;;;;;;;;;;;;;

[Registration Server 1]
                       ;dispatch.jack.com
;HTTP Server Name     = 10.0.2.2
HTTP Server Name     = 10.0.2.2
HTTP Server Port     = 8080
;;;                       ;dev.jack.com
;;;HTTP Server Name     = 10.0.2.2
;;;HTTP Server Port     = 8080
;;;HTTP Server Port     = 8042

;;;; Web Server ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Web Server]
HTTP Server Name     = 10.0.2.2
;HTTP Server Port     = 80  (commented out, no ":80" in URL)
Success Page         = /acro/sponsors.html
;Success Page         = /acrobeta/sponsors.html
Error Page	         = /acro/trouble.html
